[workspace]
members = [
    "crates/*",
    "plugins/*",
   # "lsp"
]
default-members = [
    "crates/causm-core",
    "crates/causm-concurrency",
    "crates/causm-ir",
    "crates/causm-frontend",
    "crates/causm-analysis",
    "crates/causm-runtime",
    "crates/causm-stdlib",
    "crates/causm-devtools",
    "crates/causm-cli",
]
resolver = "2"

[workspace.package]
version = "0.1.0-alpha.1"
edition = "2021"
authors = [
    "Seuriin (SSL-ACTX) <seuriin@gmail.com>",
    "Iris-Seravelle (Iris's GPG) <iris.seravelle@gmail.com>",
]
license = "AGPL-3.0-only"
repository = "https://github.com/SSL-ACTX/Causm"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
opt-level = 0
debug = 1
strip = true
panic = "unwind"
lto = false
codegen-units = 256

[profile.test]
opt-level = 0
debug = 1

