use super::facts::PointIndex;
use std::fmt;

/// Precise, multi-span relational diagnostic generated by the Entropius solver.
///
/// Unlike lexical compilers that only point to the error site, this stores the
/// complete relational trace across the Control Flow Graph: origin, consume, and
/// illegal access points, each with real source location and text.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EntropicDiagnostic {
    /// Invariant 1: Absence of Use-After-Consume.
    UseAfterConsume {
        var: String,
        origin_point: Option<PointIndex>,
        consume_point: PointIndex,
        access_point: PointIndex,
        smt_formula: String,
    },
    /// Invariant 2: Absence of Use-After-Decay (Temporal Invariant).
    TemporalUseAfterDecay {
        var: String,
        decay_point: PointIndex,
        access_point: PointIndex,
        t_expire_ms: u64,
        t_access_ms: u64,
        smt_formula: String,
    },
    /// Invariant 3: Structural Integrity Invariant (Field Decay).
    CompoundStructFieldDecay {
        var: String,
        field: String,
        field_consume_point: PointIndex,
        struct_access_point: PointIndex,
        smt_formula: String,
    },
    /// Active Lease Safety Violation.
    LeaseConflict {
        source_var: String,
        lease_id: String,
        lease_point: PointIndex,
        consume_point: PointIndex,
        t_start_ms: u64,
        t_end_ms: u64,
        smt_formula: String,
    },
    /// Causal Paradox Violation (Rewind past causal commitment).
    CausalParadox {
        anchor_name: String,
        anchor_point: PointIndex,
        rewind_point: PointIndex,
        commit_point: PointIndex,
        anchor_clock: u64,
        horizon_clock: u64,
        smt_formula: String,
    },
    /// Entanglement Conflict Violation (Accessing variable decayed via entangled partner's consumption).
    EntanglementConflict {
        var: String,
        partner_var: String,
        partner_consume_point: PointIndex,
        access_point: PointIndex,
        smt_formula: String,
    },
}


/// Render a single source span annotation block with optional token highlighting.
///
/// If `highlight` is `Some(token)`, the underline (`^^^`) is placed under that
/// token's position in the source line. Otherwise falls back to the statement start col.
fn find_word_token(src: &str, tok: &str) -> Option<(usize, usize)> {
    let mut offset = 0;
    while let Some(idx) = src[offset..].find(tok) {
        let abs_pos = offset + idx;
        let before_ok = abs_pos == 0 || !src[..abs_pos].chars().last().unwrap().is_alphanumeric() && src[..abs_pos].chars().last().unwrap() != '_';
        let after_pos = abs_pos + tok.len();
        let after_ok = after_pos >= src.len() || !src[after_pos..].chars().next().unwrap().is_alphanumeric() && src[after_pos..].chars().next().unwrap() != '_';
        if before_ok && after_ok {
            return Some((abs_pos, tok.len()));
        }
        offset = abs_pos + 1;
    }
    None
}

/// Render a single source span annotation block with contextual styling.
fn render_span(pt: &PointIndex, label: &str, highlight: Option<&str>) -> String {
    let mut out = String::new();
    if pt.line == 0 {
        out.push_str(&format!("\x1b[1;34m  --> \x1b[0m{}:?:?\n\x1b[1;34m   |\x1b[0m\n   = {}\n", pt.file, label));
        return out;
    }
    let line_num_width = pt.line.to_string().len().max(2);
    let pad = " ".repeat(line_num_width);
    let src = pt.source_text.trim_end();

    // Prefer exact word boundary token match
    let (ul_start, ul_len) = if let Some(tok) = highlight {
        if let Some((pos, len)) = find_word_token(src, tok) {
            (pos, len)
        } else if let Some(pos) = src.find(tok) {
            (pos, tok.len())
        } else {
            let col0 = pt.col.saturating_sub(1);
            let tlen = src[col0..].split_whitespace().next().map(|t| t.len()).unwrap_or(1);
            (col0, tlen)
        }
    } else {
        let col0 = pt.col.saturating_sub(1);
        let tlen = src[col0..].split_whitespace().next().map(|t| t.len()).unwrap_or(1);
        (col0, tlen)
    };
    let display_col = ul_start + 1;

    out.push_str(&format!("\x1b[1;34m  --> \x1b[0m{}:{}:{}\n", pt.file, pt.line, display_col));
    out.push_str(&format!("\x1b[1;34m{pad} |\x1b[0m\n"));
    let underline = " ".repeat(ul_start) + &"^".repeat(ul_len.max(1));

    out.push_str(&format!("\x1b[1;34m{:>width$} | \x1b[0m{}\n", pt.line, src, width = line_num_width));
    out.push_str(&format!("\x1b[1;34m{pad} | \x1b[1;31m{}\x1b[0m {}\n", underline, label));
    out.push_str(&format!("\x1b[1;34m{pad} |\x1b[0m\n"));
    out
}

/// Render the formal SMT constraint block.
fn render_smt(formula: &str) -> String {
    let mut out = String::new();
    out.push_str("   = note[SMT]: formal entropic constraint (UNSAT proof)\n");
    out.push_str(&format!("               {}\n", formula));
    out
}

impl EntropicDiagnostic {
    /// Returns the formal First-Order Relational / SMT formula associated with this failure.
    pub fn formula(&self) -> &str {
        match self {
            Self::UseAfterConsume { smt_formula, .. }
            | Self::TemporalUseAfterDecay { smt_formula, .. }
            | Self::CompoundStructFieldDecay { smt_formula, .. }
            | Self::LeaseConflict { smt_formula, .. }
            | Self::CausalParadox { smt_formula, .. }
            | Self::EntanglementConflict { smt_formula, .. } => smt_formula,
        }
    }

    /// Formats the diagnostic with precise multi-span source annotations,
    /// `^^^` token underlines at each relevant point, and the formal SMT UNSAT constraint.
    pub fn format_diagnostic(&self, include_smt_formula: bool) -> String {
        let mut out = String::new();
        match self {
            Self::UseAfterConsume {
                var,
                origin_point,
                consume_point,
                access_point,
                smt_formula,
            } => {
                out.push_str(&format!(
                    "[1;31merror[E0001][0m:[1m use of consumed variable `{var}`[0m\n"
                ));
                if let Some(orig) = origin_point {
                    out.push_str(&render_span(orig, &format!("`{var}` value introduced here"), Some(var)));
                }
                out.push_str(&render_span(
                    consume_point,
                    &format!("`{var}` linearly consumed here — ownership transferred"),
                    Some(var),
                ));
                out.push_str(&render_span(
                    access_point,
                    &format!("illegal: `{var}` used here after being consumed"),
                    Some(var),
                ));
                out.push_str(&format!(
                    "   = help: variable `{var}` follows linear ownership; once consumed it cannot be reused.\n"
                ));
                out.push_str(
                    "   = help: consider cloning before consuming, or restructure so the value is used at most once.\n",
                );
                if include_smt_formula {
                    out.push_str(&render_smt(smt_formula));
                }
            }

            Self::TemporalUseAfterDecay {
                var,
                decay_point,
                access_point,
                t_expire_ms,
                t_access_ms,
                smt_formula,
            } => {
                out.push_str(&format!(
                    "[1;31merror[E0002][0m:[1m use of temporally decayed variable `{var}`[0m\n"
                ));
                out.push_str(&render_span(
                    decay_point,
                    &format!("`{var}` lifetime expires at clock {t_expire_ms}ms"),
                    Some(var),
                ));
                out.push_str(&render_span(
                    access_point,
                    &format!(
                        "illegal: `{var}` accessed at clock {t_access_ms}ms, after TTL {t_expire_ms}ms"
                    ),
                    Some(var),
                ));
                out.push_str(&format!(
                    "   = help: the lifetime annotation `decay({t_expire_ms}ms)` on `{var}` means it is invalid after {t_expire_ms}ms.\n"
                ));
                out.push_str(&format!(
                    "   = help: move the access before clock {t_expire_ms}ms, or extend the lifetime annotation.\n"
                ));
                if include_smt_formula {
                    out.push_str(&render_smt(smt_formula));
                }
            }

            Self::CompoundStructFieldDecay {
                var,
                field,
                field_consume_point,
                struct_access_point,
                smt_formula,
            } => {
                out.push_str(&format!(
                    "[1;31merror[E0003][0m:[1m use of structurally decayed struct `{var}` after field `{field}` was consumed\n"
                ));
                let field_path = format!("{var}.{field}");
                out.push_str(&render_span(
                    field_consume_point,
                    &format!("field `{var}.{field}` linearly consumed here"),
                    Some(&field_path),
                ));
                out.push_str(&render_span(
                    struct_access_point,
                    &format!("illegal: struct `{var}` accessed here but `{field}` is gone"),
                    Some(var),
                ));
                out.push_str(
                    "   = help: consuming a field invalidates the owning struct under Invariant 3.\n",
                );
                out.push_str(&format!(
                    "   = help: destructure all fields before use, or do not consume `{var}.{field}` before accessing `{var}`.\n"
                ));
                if include_smt_formula {
                    out.push_str(&render_smt(smt_formula));
                }
            }

            Self::LeaseConflict {
                source_var,
                lease_id,
                lease_point,
                consume_point,
                t_start_ms,
                t_end_ms,
                smt_formula,
            } => {
                out.push_str(&format!(
                    "[1;31merror[E0004][0m:[1m cannot consume `{source_var}` while active lease `{lease_id}` is held\n"
                ));
                out.push_str(&render_span(
                    lease_point,
                    &format!(
                        "lease `{lease_id}` granted here for interval [{t_start_ms}ms, {t_end_ms}ms]"
                    ),
                    Some(lease_id),
                ));
                out.push_str(&render_span(
                    consume_point,
                    &format!("illegal: `{source_var}` consumed here while lease is active"),
                    Some(source_var),
                ));
                out.push_str(
                    "   = help: a leased variable cannot be consumed until the lease block exits and the lease is dropped.\n",
                );
                if include_smt_formula {
                    out.push_str(&render_smt(smt_formula));
                }
            }

            Self::CausalParadox {
                anchor_name,
                anchor_point,
                rewind_point,
                commit_point,
                anchor_clock,
                horizon_clock,
                smt_formula,
            } => {
                out.push_str(&format!(
                    "[1;31merror[E0005][0m:[1m Causal Paradox — rewind to anchor `{anchor_name}` violates causal horizon\n"
                ));
                out.push_str(&render_span(
                    anchor_point,
                    &format!("anchor `{anchor_name}` established at clock {anchor_clock}ms"),
                    Some(anchor_name),
                ));
                out.push_str(&render_span(
                    commit_point,
                    &format!("irreversible commitment established causal horizon at clock {horizon_clock}ms"),
                    None,
                ));
                out.push_str(&render_span(
                    rewind_point,
                    &format!("illegal: cannot rewind back to {anchor_clock}ms past causal horizon {horizon_clock}ms"),
                    Some(anchor_name),
                ));
                out.push_str(
                    "   = help: commitments (e.g. yield, external I/O) are irreversible; timeline cannot rewind past them.\n",
                );
                if include_smt_formula {
                    out.push_str(&render_smt(smt_formula));
                }
            }

            Self::EntanglementConflict {
                var,
                partner_var,
                partner_consume_point,
                access_point,
                smt_formula,
            } => {
                out.push_str(&format!(
                    "[1;31merror[E0006][0m:[1m use of entangled variable `{var}` decayed after partner `{partner_var}` was consumed\n"
                ));
                out.push_str(&render_span(
                    partner_consume_point,
                    &format!("entangled partner `{partner_var}` linearly consumed here"),
                    Some(partner_var),
                ));
                out.push_str(&render_span(
                    access_point,
                    &format!("illegal: `{var}` is decayed due to entanglement with `{partner_var}`"),
                    Some(var),
                ));
                out.push_str(
                    "   = help: entangling variables links their entropic states; consuming one collapses the entire entangled set.\n",
                );
                if include_smt_formula {
                    out.push_str(&render_smt(smt_formula));
                }
            }
        }
        out
    }
}

impl fmt::Display for EntropicDiagnostic {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.format_diagnostic(true))
    }
}
