// causm-kernel/bindings/causm-kernel-sys/src/lib.rs
//! Zero-cost safe Rust FFI bindings for the verified Causm microkernel.
//!
//! Provides mathematically checked linear memory arena operations, isochronous
//! WCET budget tracking, operational instruction stepping, entanglement cascade,
//! CFG basic block execution, and static type well-formedness verification.

/// Low-level C FFI definitions generated by KaRaMeL from verified Pulse implementations.
pub mod ffi {
    #[repr(C)]
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub struct Pulse_Causm_Arena_cell_t {
        pub payload: u64,
        pub tag: u32,
        pub expire: u64,
    }

    #[repr(C)]
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub struct Pulse_Causm_CFG_raw_instr_t {
        pub op: u32,
        pub arg1: usize,
        pub arg2: usize,
        pub arg3: usize,
        pub imm: u64,
    }

    extern "C" {
        // --- Arena Operations (Pulse.Causm.Arena) ---
        pub fn Pulse_Causm_Arena_read_valid_cell(c: *mut Pulse_Causm_Arena_cell_t) -> u64;
        pub fn Pulse_Causm_Arena_consume_cell(c: *mut Pulse_Causm_Arena_cell_t);
        pub fn Pulse_Causm_Arena_tick_cell_decay(c: *mut Pulse_Causm_Arena_cell_t, current_clk: u64);
        pub fn Pulse_Causm_Arena_lease_cell(c: *mut Pulse_Causm_Arena_cell_t, current_clk: u64, duration: u64);
        pub fn Pulse_Causm_Arena_init_valid_cell(c: *mut Pulse_Causm_Arena_cell_t, v: u64);

        pub fn Pulse_Causm_Arena_arena_read(a: *const Pulse_Causm_Arena_cell_t, idx: usize, current_clk: u64) -> u64;
        pub fn Pulse_Causm_Arena_arena_consume(a: *mut Pulse_Causm_Arena_cell_t, idx: usize);
        pub fn Pulse_Causm_Arena_arena_lease(a: *mut Pulse_Causm_Arena_cell_t, idx: usize, current_clk: u64, duration: u64);
        pub fn Pulse_Causm_Arena_arena_init_valid(a: *mut Pulse_Causm_Arena_cell_t, idx: usize, v: u64);
        pub fn Pulse_Causm_Arena_arena_tick_decay(a: *mut Pulse_Causm_Arena_cell_t, idx: usize, current_clk: u64);
        pub fn Pulse_Causm_Arena_tag_meet_u32(t1: u32, t2: u32) -> u32;
        pub fn Pulse_Causm_Arena_arena_merge_meet(dst: *mut Pulse_Causm_Arena_cell_t, idx: usize, pred_tag: u32, pred_expire: u64);

        pub fn Pulse_Causm_Arena_wcet_budget_step(consumed: *mut u64, cost: u64, max_limit: u64) -> bool;
        pub fn Pulse_Causm_Arena_wcet_isochronous_pace_step(consumed: *mut u64, cost: u64, target_pace: u64, max_limit: u64) -> bool;

        pub fn Pulse_Causm_Arena_check_cell_access(a: *const Pulse_Causm_Arena_cell_t, idx: usize, current_clk: u64) -> u32;
        pub fn Pulse_Causm_Arena_check_cell_consume(a: *const Pulse_Causm_Arena_cell_t, idx: usize) -> u32;
        pub fn Pulse_Causm_Arena_check_cell_lease(a: *const Pulse_Causm_Arena_cell_t, idx: usize, current_clk: u64, duration: u64) -> u32;

        // --- Semantics & Entanglement (Pulse.Causm.Semantics) ---
        pub fn Pulse_Causm_Semantics_is_entangled(m: *const u8, n: usize, r1: usize, r2: usize) -> bool;
        pub fn Pulse_Causm_Semantics_set_entangle_edge(m: *mut u8, n: usize, r1: usize, r2: usize);
        pub fn Pulse_Causm_Semantics_exec_load_int(regs: *mut Pulse_Causm_Arena_cell_t, dest: usize, v: u64);
        pub fn Pulse_Causm_Semantics_exec_add(regs: *mut Pulse_Causm_Arena_cell_t, dest: usize, src1: usize, src2: usize, current_clk: u64) -> bool;
        pub fn Pulse_Causm_Semantics_exec_entangle(regs: *mut Pulse_Causm_Arena_cell_t, ent_matrix: *mut u8, n: usize, r1: usize, r2: usize) -> bool;
        pub fn Pulse_Causm_Semantics_consume_entangled_sweep(regs: *mut Pulse_Causm_Arena_cell_t, ent_matrix: *const u8, n: usize, target: usize, curr: usize);
        pub fn Pulse_Causm_Semantics_exec_consume_cascading(regs: *mut Pulse_Causm_Arena_cell_t, ent_matrix: *mut u8, n: usize, target: usize) -> bool;
        pub fn Pulse_Causm_Semantics_exec_lease(regs: *mut Pulse_Causm_Arena_cell_t, target: usize, current_clk: u64, duration: u64) -> bool;

        // --- CFG Basic Block Step (Pulse.Causm.CFG) ---
        pub fn Pulse_Causm_CFG_exec_instr_step(regs: *mut Pulse_Causm_Arena_cell_t, ent_matrix: *mut u8, n: usize, current_clk: *mut u64, i: Pulse_Causm_CFG_raw_instr_t) -> bool;
        pub fn Pulse_Causm_CFG_exec_body_loop(regs: *mut Pulse_Causm_Arena_cell_t, ent_matrix: *mut u8, n: usize, current_clk: *mut u64, body: *const Pulse_Causm_CFG_raw_instr_t, body_len: usize, pc: usize) -> bool;

        // --- Static Type Checker (Pulse.Causm.TypeChecker) ---
        pub fn Pulse_Causm_TypeChecker_verify_instruction_typing(regs: *const Pulse_Causm_Arena_cell_t, n: usize, current_clk: u64, i: Pulse_Causm_CFG_raw_instr_t) -> bool;
        pub fn Pulse_Causm_TypeChecker_verify_body_typing(regs: *mut Pulse_Causm_Arena_cell_t, ent_matrix: *mut u8, n: usize, current_clk: *mut u64, body: *const Pulse_Causm_CFG_raw_instr_t, body_len: usize, pc: usize) -> bool;
    }
}

pub use ffi::{Pulse_Causm_Arena_cell_t as CellT, Pulse_Causm_CFG_raw_instr_t as RawInstr};

/// Fine-grained diagnostic error codes generated directly by the verified Pulse microkernel.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KernelDiagnostic {
    Ok,
    UseAfterConsume,
    UseAfterDecay,
    LeaseExpired,
    DoubleConsume,
    ConsumeDecayed,
    ConsumeActiveLease,
    CannotLeaseNonValid,
    LeaseDurationOverflow,
    IndexOutOfBounds,
}

impl KernelDiagnostic {
    pub fn is_ok(self) -> bool {
        matches!(self, KernelDiagnostic::Ok)
    }
}

/// A formally verified linear register arena backed by the Pulse microkernel.
#[derive(Debug, Clone)]
pub struct Arena {
    cells: Vec<CellT>,
}

impl Arena {
    pub fn new(size: usize) -> Self {
        Self {
            cells: vec![
                CellT {
                    payload: 0,
                    tag: 3, // Initial state: TagConsumed
                    expire: 0,
                };
                size
            ],
        }
    }

    #[inline]
    pub fn len(&self) -> usize {
        self.cells.len()
    }

    #[inline]
    pub fn is_empty(&self) -> bool {
        self.cells.is_empty()
    }

    #[inline]
    pub fn get_cell(&self, idx: usize) -> Option<CellT> {
        self.cells.get(idx).copied()
    }

    #[inline]
    pub fn read(&self, idx: usize) -> Option<u64> {
        self.read_at(idx, 0)
    }

    #[inline]
    pub fn read_at(&self, idx: usize, current_clk: u64) -> Option<u64> {
        if let Some(cell) = self.cells.get(idx) {
            if cell.tag == 0 || (cell.tag == 1 && current_clk < cell.expire) {
                return Some(unsafe {
                    ffi::Pulse_Causm_Arena_arena_read(self.cells.as_ptr(), idx, current_clk)
                });
            }
        }
        None
    }

    #[inline]
    pub fn consume(&mut self, idx: usize) -> bool {
        if let Some(cell) = self.cells.get(idx) {
            if cell.tag == 0 {
                unsafe { ffi::Pulse_Causm_Arena_arena_consume(self.cells.as_mut_ptr(), idx) };
                return true;
            }
        }
        false
    }

    #[inline]
    pub fn lease(&mut self, idx: usize, current_clk: u64, duration: u64) -> bool {
        if let Some(cell) = self.cells.get(idx) {
            if cell.tag == 0 && current_clk.checked_add(duration).is_some() {
                unsafe { ffi::Pulse_Causm_Arena_arena_lease(self.cells.as_mut_ptr(), idx, current_clk, duration) };
                return true;
            }
        }
        false
    }

    #[inline]
    pub fn init_valid(&mut self, idx: usize, v: u64) -> bool {
        if idx < self.cells.len() {
            unsafe { ffi::Pulse_Causm_Arena_arena_init_valid(self.cells.as_mut_ptr(), idx, v) };
            true
        } else {
            false
        }
    }

    #[inline]
    pub fn check_access(&self, idx: usize, current_clk: u64) -> KernelDiagnostic {
        if idx >= self.cells.len() {
            return KernelDiagnostic::IndexOutOfBounds;
        }
        let code = unsafe {
            ffi::Pulse_Causm_Arena_check_cell_access(self.cells.as_ptr(), idx, current_clk)
        };
        match code {
            0 => KernelDiagnostic::Ok,
            1 => KernelDiagnostic::UseAfterConsume,
            2 => KernelDiagnostic::UseAfterDecay,
            3 => KernelDiagnostic::LeaseExpired,
            _ => KernelDiagnostic::UseAfterConsume,
        }
    }

    #[inline]
    pub fn check_consume(&self, idx: usize) -> KernelDiagnostic {
        if idx >= self.cells.len() {
            return KernelDiagnostic::IndexOutOfBounds;
        }
        let code = unsafe {
            ffi::Pulse_Causm_Arena_check_cell_consume(self.cells.as_ptr(), idx)
        };
        match code {
            0 => KernelDiagnostic::Ok,
            4 => KernelDiagnostic::DoubleConsume,
            5 => KernelDiagnostic::ConsumeDecayed,
            6 => KernelDiagnostic::ConsumeActiveLease,
            _ => KernelDiagnostic::DoubleConsume,
        }
    }

    #[inline]
    pub fn check_lease(&self, idx: usize, current_clk: u64, duration: u64) -> KernelDiagnostic {
        if idx >= self.cells.len() {
            return KernelDiagnostic::IndexOutOfBounds;
        }
        let code = unsafe {
            ffi::Pulse_Causm_Arena_check_cell_lease(self.cells.as_ptr(), idx, current_clk, duration)
        };
        match code {
            0 => KernelDiagnostic::Ok,
            7 => KernelDiagnostic::CannotLeaseNonValid,
            8 => KernelDiagnostic::LeaseDurationOverflow,
            _ => KernelDiagnostic::CannotLeaseNonValid,
        }
    }

    pub fn state_partition(&self) -> (usize, usize, usize, usize) {
        let mut valid = 0;
        let mut leased = 0;
        let mut decayed = 0;
        let mut consumed = 0;
        for c in &self.cells {
            match c.tag {
                0 => valid += 1,
                1 => leased += 1,
                2 => decayed += 1,
                _ => consumed += 1,
            }
        }
        (valid, leased, decayed, consumed)
    }

    pub fn tick_sweep(&mut self, current_clk: u64) {
        for idx in 0..self.cells.len() {
            if self.cells[idx].tag == 1 && current_clk >= self.cells[idx].expire {
                unsafe { ffi::Pulse_Causm_Arena_arena_tick_decay(self.cells.as_mut_ptr(), idx, current_clk) };
            }
        }
    }

    pub fn merge_from(&mut self, other: &Arena) {
        let min_len = self.cells.len().min(other.cells.len());
        for idx in 0..min_len {
            unsafe {
                ffi::Pulse_Causm_Arena_arena_merge_meet(
                    self.cells.as_mut_ptr(),
                    idx,
                    other.cells[idx].tag,
                    other.cells[idx].expire,
                );
            }
        }
    }
}

/// A complete verified VM execution environment with register arena and entanglement graph.
#[derive(Debug, Clone)]
pub struct VerifiedVM {
    pub arena: Arena,
    entangle_matrix: Vec<u8>,
    pub clock: u64,
}

impl VerifiedVM {
    pub fn new(num_regs: usize) -> Self {
        Self {
            arena: Arena::new(num_regs),
            entangle_matrix: vec![0; num_regs * num_regs],
            clock: 0,
        }
    }

    #[inline]
    pub fn num_regs(&self) -> usize {
        self.arena.len()
    }

    #[inline]
    pub fn is_entangled(&self, r1: usize, r2: usize) -> bool {
        let n = self.arena.len();
        if r1 < n && r2 < n {
            unsafe { ffi::Pulse_Causm_Semantics_is_entangled(self.entangle_matrix.as_ptr(), n, r1, r2) }
        } else {
            false
        }
    }

    #[inline]
    pub fn entangle(&mut self, r1: usize, r2: usize) -> bool {
        let n = self.arena.len();
        if r1 < n && r2 < n && r1 != r2 {
            unsafe {
                ffi::Pulse_Causm_Semantics_exec_entangle(
                    self.arena.cells.as_mut_ptr(),
                    self.entangle_matrix.as_mut_ptr(),
                    n,
                    r1,
                    r2,
                )
            }
        } else {
            false
        }
    }

    #[inline]
    pub fn consume_cascading(&mut self, target: usize) -> bool {
        let n = self.arena.len();
        if target < n {
            unsafe {
                ffi::Pulse_Causm_Semantics_exec_consume_cascading(
                    self.arena.cells.as_mut_ptr(),
                    self.entangle_matrix.as_mut_ptr(),
                    n,
                    target,
                )
            }
        } else {
            false
        }
    }

    #[inline]
    pub fn step_instruction(&mut self, instr: RawInstr) -> bool {
        let n = self.arena.len();
        unsafe {
            ffi::Pulse_Causm_CFG_exec_instr_step(
                self.arena.cells.as_mut_ptr(),
                self.entangle_matrix.as_mut_ptr(),
                n,
                &mut self.clock,
                instr,
            )
        }
    }

    #[inline]
    pub fn verify_instruction_typing(&self, instr: RawInstr) -> bool {
        let n = self.arena.len();
        unsafe {
            ffi::Pulse_Causm_TypeChecker_verify_instruction_typing(
                self.arena.cells.as_ptr(),
                n,
                self.clock,
                instr,
            )
        }
    }

    pub fn execute_basic_block(&mut self, body: &[RawInstr]) -> bool {
        let n = self.arena.len();
        unsafe {
            ffi::Pulse_Causm_CFG_exec_body_loop(
                self.arena.cells.as_mut_ptr(),
                self.entangle_matrix.as_mut_ptr(),
                n,
                &mut self.clock,
                body.as_ptr(),
                body.len(),
                0,
            )
        }
    }

    pub fn verify_and_execute_basic_block(&mut self, body: &[RawInstr]) -> bool {
        let n = self.arena.len();
        unsafe {
            ffi::Pulse_Causm_TypeChecker_verify_body_typing(
                self.arena.cells.as_mut_ptr(),
                self.entangle_matrix.as_mut_ptr(),
                n,
                &mut self.clock,
                body.as_ptr(),
                body.len(),
                0,
            )
        }
    }
}

/// A formally verified isochronous WCET budget tracker backed by the Pulse microkernel.
#[derive(Debug, Clone)]
pub struct IsochronousTracker {
    consumed: u64,
    max_limit: u64,
}

impl IsochronousTracker {
    pub fn new(max_limit: u64) -> Self {
        Self {
            consumed: 0,
            max_limit,
        }
    }

    #[inline]
    pub fn consumed(&self) -> u64 {
        self.consumed
    }

    #[inline]
    pub fn max_limit(&self) -> u64 {
        self.max_limit
    }

    #[inline]
    pub fn remaining(&self) -> u64 {
        self.max_limit.saturating_sub(self.consumed)
    }

    #[inline]
    pub fn try_step(&mut self, cost: u64) -> bool {
        unsafe {
            ffi::Pulse_Causm_Arena_wcet_budget_step(&mut self.consumed, cost, self.max_limit)
        }
    }

    #[inline]
    pub fn try_pace_step(&mut self, cost: u64, target_pace: u64) -> bool {
        unsafe {
            ffi::Pulse_Causm_Arena_wcet_isochronous_pace_step(&mut self.consumed, cost, target_pace, self.max_limit)
        }
    }
}
