[target.aarch64-linux-android]
#rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[alias]
build-plugins = "build --package seccomp_guard --target wasm32-unknown-unknown -j 4"
build-all = "build --workspace"

test-slow = "test -j 4"
test-all = "test --workspace"
